export const phonesMocks = [
  {
    id: 0,
    name: "Apple iPhone 12",
    image: "apple-iphone-12.png",
    brand: "Apple",
    release: "2020",
    screenDiagonal: "6,1",
    country: "Китай",
    memorySize: "128 Гб",
    screenRefreshRate: "60 Гц",
    nfc: false,
    esimSupport: true,
    wirelessCharger: true,
    cost: "81 990",
  },
  {
    id: 1,
    name: "Xiaomi Mi 11 Lite",
    image: "xiaomi-mi-11-lite-1.png",
    brand: "Xiaomi",
    release: "2021",
    screenDiagonal: "6,55",
    country: "Китай",
    memorySize: "128 Гб",
    screenRefreshRate: "90 Гц",
    nfc: true,
    esimSupport: true,
    wirelessCharger: false,
    cost: "27 490",
  },
  {
    id: 2,
    name: "Samsung Galaxy A72",
    image: "samsung-galaxy-a72.png",
    brand: "Samsung",
    release: "2021",
    screenDiagonal: "6,7",
    country: "Вьетнам",
    memorySize: "128 Гб",
    screenRefreshRate: "90 Гц",
    nfc: true,
    esimSupport: false,
    wirelessCharger: true,
    cost: "32 890",
  },
  {
    id: 3,
    name: "Samsung Galaxy S21",
    image: "samsung-galaxy-s21.png",
    brand: "Samsung",
    release: "2019",
    screenDiagonal: "6,0",
    country: "Китай",
    memorySize: "128 Гб",
    screenRefreshRate: "90 Гц",
    nfc: true,
    esimSupport: false,
    wirelessCharger: true,
    cost: "71 995",
  },
  {
    id: 4,
    name: "Apple iPhone Xr",
    image: "apple-iphone-xr.png",
    brand: "Apple",
    release: "2020",
    screenDiagonal: "7,0",
    country: "Китай",
    memorySize: "256 Гб",
    screenRefreshRate: "90 Гц",
    nfc: false,
    esimSupport: false,
    wirelessCharger: true,
    cost: "49 990",
  },
  {
    id: 5,
    name: "Realme 8 Pro",
    image: "realme-8-pro.png",
    brand: "Realme",
    release: "2018",
    screenDiagonal: "6,8",
    country: "Китай",
    memorySize: "128 Гб",
    screenRefreshRate: "90 Гц",
    nfc: true,
    esimSupport: true,
    wirelessCharger: true,
    cost: "26 990",
  },
  {
    id: 6,
    name: "Realme 8 Pro",
    image: "realme-8-pro.png",
    brand: "Realme",
    release: "2018",
    screenDiagonal: "6,8",
    country: "Китай",
    memorySize: "128 Гб",
    screenRefreshRate: "90 Гц",
    nfc: true,
    esimSupport: true,
    wirelessCharger: true,
    cost: "26 990",
  },
];